### ISSUE TITLE
Error installing requirements.txt on PC

### ISSUE THREAD

**Issue by AvenCores** [WHITEDH4CKER/SMSBOMB#1]
(venv) C:\Users\avencores\Downloads\SMSBOMB-main>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement certifi>=2023.08.08 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 1.0.0, 1.0.1, 14.5.14, 2015.4.28, 2015.9.6, 2015.9.6.1, 2015.9.6.2, 2015.11.20, 2015.11.20.1, 2016.2.28, 2016.8.2, 2016.8.8, 2016.8.31, 2016.9.26, 2017.1.23, 2017.4.17, 2017.7.27, 2017.7.27.1, 2017.11.5, 2018.1.18, 2018.4.16, 2018.8.13, 2018.8.24, 2018.10.15, 2018.11.29, 2019.3.9, 2019.6.16, 2019.9.11, 2019.11.28, 2020.4.5, 2020.4.5.1, 2020.4.5.2, 2020.6.20, 2020.11.8, 2020.12.5, 2021.5.30, 2021.10.8, 2022.5.18, 2022.5.18.1, 2022.6.15, 2022.6.15.1, 2022.6.15.2, 2022.9.14, 2022.9.24, 2022.12.7, 2023.5.7, 2023.7.22)
ERROR: No matching distribution found for certifi>=2023.08.08

FIX to requirements.txt:
certifi
chardet
colorama
idna
requests

**Comment by WHITEDH4CKER** [comment]
apt install pip
pip install colorama
pip install -r requirements.txt
